[package]
name = "monster-regex"
description = "A custom regex spec"
version = "0.2.6"
edition = "2024"
license = "MIT"
repository = "https://github.com/monster0506/monster-regex"
documentation = "https://docs.rs/monster-regex"

[dependencies]
memchr = "2.7.6"

[features]
default = []
internal_metrics = []

[dev-dependencies]
criterion = "0.5"
regex = "1"

[[bench]]
name = "main"
harness = false

[[bench]]
name = "vs_regex"
harness = false

[profile.release]
lto = "thin"
codegen-units = 1